name: eln
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - streamlit==1.29.0
    - sqlalchemy==2.0.23
    - pandas==2.1.4
    - fpdf2==2.7.6
    - markdown==3.5.1
    - python-markdown-math==0.8.0
    - pillow==10.1.0
    - python-dateutil==2.8.2
